# Generated by Django 2.1.dev20180410172650 on 2018-04-11 21:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('done_oocytes', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10)])),
                ('year', models.IntegerField()),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('water_temp', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_img', models.CharField(max_length=50)),
                ('binarized_img', models.CharField(max_length=50)),
                ('crab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crabgame.Crab')),
            ],
        ),
        migrations.CreateModel(
            name='Intermediate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Oocyte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chosen_count', models.IntegerField(default=0)),
                ('area', models.IntegerField(default=0)),
                ('center_x', models.FloatField()),
                ('center_y', models.FloatField()),
                ('crab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crabgame.Crab')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crabgame.Image')),
            ],
        ),
        migrations.CreateModel(
            name='PlaySession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_photos', models.IntegerField(default=10)),
                ('completed_photos', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('className', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='intermediate',
            name='oocyte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crabgame.Oocyte'),
        ),
        migrations.AddField(
            model_name='intermediate',
            name='schoolClass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crabgame.SchoolClass'),
        ),
        migrations.AddField(
            model_name='intermediate',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crabgame.PlaySession'),
        ),
    ]
