# Generated by Django 2.0.3 on 2018-04-13 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crabgame', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='csv',
            field=models.CharField(default='test.csv', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='crab',
            name='year',
            field=models.IntegerField(default=2018),
        ),
        migrations.AlterField(
            model_name='image',
            name='binarized_img',
            field=models.ImageField(height_field=486, upload_to='uploads/crab.id', width_field=648),
        ),
        migrations.AlterField(
            model_name='image',
            name='original_img',
            field=models.ImageField(height_field=486, upload_to='uploads/crab.id', width_field=648),
        ),
        migrations.AlterField(
            model_name='oocyte',
            name='area',
            field=models.IntegerField(),
        ),
    ]
