# Generated by Django 2.0.3 on 2018-04-14 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crabgame', '0003_auto_20180414_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='crab',
            name='sample_num',
            field=models.IntegerField(default=0),
        ),
    ]
