# Generated by Django 2.0.4 on 2018-04-14 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crabgame', '0004_crab_sample_num'),
        ('crabgame', '0002_auto_20180413_1616'),
    ]

    operations = [
    ]
