# Generated by Django 2.0.3 on 2018-04-17 19:32

import crabgame.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crabgame', '0005_merge_20180414_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='binarized_img',
            field=models.ImageField(upload_to=crabgame.models.get_upload_path),
        ),
        migrations.AlterField(
            model_name='image',
            name='original_img',
            field=models.ImageField(upload_to=crabgame.models.get_upload_path),
        ),
    ]
