# Generated by Django 2.0.3 on 2018-04-18 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crabgame', '0006_auto_20180417_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playsession',
            name='num_photos',
            field=models.IntegerField(default=12),
        ),
    ]
