# Generated by Django 2.0.3 on 2018-04-29 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crabgame', '0007_auto_20180418_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playsession',
            name='num_photos',
            field=models.IntegerField(default=8),
        ),
    ]
