# Generated by Django 2.0.4 on 2018-05-03 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crabgame', '0008_auto_20180429_2227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intermediate',
            name='oocyte',
        ),
        migrations.RemoveField(
            model_name='intermediate',
            name='schoolClass',
        ),
        migrations.RemoveField(
            model_name='intermediate',
            name='session',
        ),
        migrations.DeleteModel(
            name='Intermediate',
        ),
        migrations.DeleteModel(
            name='SchoolClass',
        ),
    ]
