# Generated by Django 2.0.4 on 2018-05-05 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crabgame', '0009_auto_20180503_1354'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaySessionImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crabgame.Image')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crabgame.PlaySession')),
            ],
        ),
    ]
