# Generated by Django 2.0.4 on 2018-05-06 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crabgame', '0010_playsessionimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='crab',
            name='shell_condition',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
